### ISSUE TITLE
Inquiry of `jobs/qwen2_vl/qwen2vl_template.sh`

### ISSUE THREAD

**Issue by zengxingchen** [MengLcool/SliMM#1]
Thank you for your outstanding work on this project. It's exciting to see the progress you've made, especially as I have been working on similar initiatives --- train Qwen2-VL in a data-available framework.

I did notice that the file `jobs/qwen2_vl/qwen2vl_template.sh`, which is referenced in the training scripts, appears to be missing from the current repo . Could you please verify this?

**Comment by MengLcool** [comment]
Thank you for your interest in our work! Apologies for the mistakes in the training scripts introduced during code cleanup. I’ve resolved them, so please check our latest commit. Feel free to reach out if you have any questions!
